export async function main(iJustReallyWantToPissOffXsinxWithThisCodeForNoReasonAtAll) {
    iJustReallyWantToPissOffXsinxWithThisCodeForNoReasonAtAll.grow(iJustReallyWantToPissOffXsinxWithThisCodeForNoReasonAtAll.args[0]);
}