export async function main(iJustReallyWantToPissOffXsinxWithThisCodeForNoReasonAtAll) {
    iJustReallyWantToPissOffXsinxWithThisCodeForNoReasonAtAll.hack(iJustReallyWantToPissOffXsinxWithThisCodeForNoReasonAtAll.args[0]);
}