export async function main(iJustReallyWantToPissOffXsinxWithThisCodeForNoReasonAtAll) {
    iJustReallyWantToPissOffXsinxWithThisCodeForNoReasonAtAll.weaken(iJustReallyWantToPissOffXsinxWithThisCodeForNoReasonAtAll.args[0]);
}